### ISSUE TITLE
Struct does not add one file to project

### ISSUE THREAD

**Issue by maximkhatskevich** [workshop/struct#102]
For some reason, it skips just one file in the project. See screenshot, notices that file "Feature.actualization.swift" is the only one missing in project navigator and is available for adding to the project.

<img width="955" alt="screen shot 2017-04-16 at 4 37 28 pm" src="https://cloud.githubusercontent.com/assets/2624646/25075169/0763cd9e-22c3-11e7-9610-bc6242a96d35.png">

Is it somehow related to #99 due to more than one dot in file name?

**Comment by lyptt** [comment]
Hi @maximkhatskevich, thanks for filing this issue. 

I don't think it's related to #99 because every other file with two dots e.g. Feature.deinitialization.swift has been added fine. Can you please provide your spec file?

**Comment by maximkhatskevich** [comment]
@lyptt sure, here is the spec file, nothing special there https://github.com/XCEssentials/UniFlow/blob/master/project.yml

**Comment by lyptt** [comment]
Hi @maximkhatskevich, apologies for not getting back to you sooner, I've been a tad busy! Could you try updating to 2.0.0 and confirm if you're still experiencing this issue?

I attempted to investigate and found it difficult to determine why you were experiencing this bug, so any more information you can provide would be extremely helpful!

**Comment by maximkhatskevich** [comment]
Thanks for the update! I'll keep testing, and will let you know if the issue still persists.
