### ISSUE TITLE
2.0?

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#103]
Is this still being worked on?
I was waiting for the 2.0.0 release before investing in this, but the release milestone for that has come and gone

**Comment by lyptt** [comment]
Hey @yonaskolb! Thanks for filing this issue. Yes it's still being worked on, I've been a tad busy this past few weeks so I haven't had a chance to fix that final bug and do a bit of testing. I'll get the release out by tomorrow.

**Comment by yonaskolb** [comment]
Is tvOS supported at the moment?

**Comment by lyptt** [comment]
I believe the existing version supports tvOS, 2.0 definitely does although potentially only basic application targets at the moment.

**Comment by lyptt** [comment]
Hi @yonaskolb! I've just released 2.0.0. Please note this is a fairly major upgrade as you'll see from the release notes, so if you encounter any oddities not captured by our automated tests please feel free to file an issue!
