### ISSUE TITLE
2.0 Migration

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#104]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

[2.0.0]

It seems that when migrating a project to yaml in version 2.0.0, it still creates a 1.3.0 `project.yml` file

**Comment by lyptt** [comment]
Hi @yonaskolb, this is now fixed in 2.0.1.
