### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#105]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

[2.0.0]

## Spec version

[2.0.0]

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

Trying to generate a `platform: tv` target and get an error

## Reproduction steps

Have a `project.yml` that specifies a target with the following:
```
targets:
  tvOS:
    sources: tvOS
    platform: tv
    type: ":application"
```
And then `struct generate`
## Expected result

Generates an `xcodeproj` file

## Actual result

Receive the following error
```
No such file or directory @ rb_sysopen - /Users/Yonas/.rvm/gems/ruby-2.4.0/gems/struct-2.0.0/lib/utils/../../res/target_config_profiles/platform_tv.yml
```

By the way, would it make sense the name the platforms how apple names them?
- iOS
- tvOS
- macOS
- watchOS

**Comment by lyptt** [comment]
Hi @yonaskolb, this is now fixed in 2.0.1.
