### ISSUE TITLE
Add support for specifying build configurations for scheme phases

### ISSUE THREAD

**Issue by lyptt** [workshop/struct#108]
Currently we only support specifying build configurations for the test phase of a scheme, this should be extended to support specifying configurations for all phases of a scheme.

In addition, the build configuration mapping needs to be able to support custom build configurations, to support the scenario when only custom build configurations are present, and the original debug/Debug and release/Release configurations are missing from a project.

**Comment by yonaskolb** [comment]
This seems to be the only thing holding us back from moving to Struct, so looking forward to getting this implemented!

**Comment by lyptt** [comment]
Hi @yonaskolb, I'm working on a few improvements to Struct today, I'll try and get this in for the next release!

**Comment by lyptt** [comment]
This is now fixed in Struct 2.1.0 / Spec 2.1.0. You should be able to take advantage of this change by specifying version '2.1.0' in your spec file.

**Comment by yonaskolb** [comment]
Thank you, much appreciated! 😀👍

**Comment by lyptt** [comment]
No problem! Let me know if you have any further issues 👍

**Comment by yonaskolb** [comment]
This doesn't seem to work... 
Specifying `build_configuration` for build types other than test doesn't do anything. Still uses default values of `debug` and `release` even though they don't exist

**Comment by lyptt** [comment]
Hi @yonaskolb, this should work, I verified the functionality as best I could before merging. For example, the [sample project](https://github.com/workshop/struct/blob/master/examples/iOS_Application/project.yml) changes the `archive` phase to use the `appstore` build configuration.

Could you please provide your project file so I can investigate further?

**Comment by yonaskolb** [comment]
Ok found the issue. It indeed works with your example. The reason it failed was because I seemingly wasn't specifying all the options. I just had:
```
archive:
      build_configuration: test release
```
As soon as the `name` parameter is added it works. I guess there are 2 issues here:
1. No warnings if something goes wrong parsing the schemes (which I assume is why it failed)
2. A lack of sensible defaults. Ideally Struct should provide defaults for all the scheme options, just like Xcode does when you create a new Scheme. This includes the `name` here in Archive, but also many other options in the other build types

**Comment by lyptt** [comment]
Hi @yonaskolb, I agree on your points. Whenever possible we do try to do those steps, I should remark though that it's a fine line when determining what constitutes as invalid when it comes to parsing. 

We're tracking a Project Linting feature (#49) that would solve this very issue, by providing common steps to fix incorrect common project configuration issues. This is currently on-going work, and it's proving to be fairly involved, but we're making good progress!

Schemes themselves are very new feature, so they definitely still need some TLC in regards to being easier to use, that I very much agree with. We'll try our best to make this happen!

**Comment by yonaskolb** [comment]
Just to add I actually just noticed that point 1 is somewhat implemented with some warnings, but not enough cover all required build type properties it seems

**Comment by lyptt** [comment]
Hi @yonaskolb, that's correct, we have a lot of these already, and #49 should make sure we've covered any possible parsing / configuration issues with warnings.

**Comment by yonaskolb** [comment]
Just a note that there is no section for `analyze` so the build configuration for that can't be set

**Comment by lyptt** [comment]
Hi @yonaskolb, I must've missed that one! I'll file a new issue for it
