### ISSUE TITLE
Variant parents

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#120]
Given that variants extend the base config, would it be useful to be able to specify a variants "parent"? This would let you create multiple abstract variants and then extend them.
This could be achieved by nesting variants (variants specifying their own variants), but then you would be forced into a single tree and wouldn't be able to share abstract variants between multiple generated variants, so maybe a `parent` property could be added to a variant

**Comment by lyptt** [comment]
Hi @yonaskolb, nice idea! I'll take this under consideration for a future release.
