### ISSUE TITLE
Target reference not found error (improve error handling for TargetReference)

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#123]
If specifying a target as a target reference, and the wrong name is supplied, generate fails with a non sensical error:
```
undefined method `configurations' for nil:NilClass
```

This is contrast to the human readable warning that is correctly show when framework can't be found when using `location: path_to_framework`:
```
Warning: Reference Carthage/Build/tvOS/BrightFutures.framework2 could not be found. Ignoring...
```

**Comment by lyptt** [comment]
Good spot! We need to clean up this error so it's more user-friendly.
