### ISSUE TITLE
Post generate doesn't run on it's own

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#127]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

[2.1.1]

## Spec version

[2.1.1]

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

The `post-generate` script doesn't run unless the `pre-generate` script is also defined.

## Reproduction steps

include the following in `project.yml`
```
scripts:
  post-generate: scripts/post-generate.rb
```

## Expected result

`scripts/post-generate.rb` script is run

## Actual result

Script isn't run. If `pre-generate` is added it does run. Interestingly, if `pre-generate` is on it's own it runs fine

**Comment by lyptt** [comment]
Interesting! Thanks for filing this. I'll aim to get this fixed up for 2.2.0
