### ISSUE TITLE
Localized resources

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#128]
In the documentation it mentions that adding localized resources is as simple as specifying a directory to find `.lproj` directories in using `i18n-resources: myTarget`
https://github.com/workshop/struct/wiki/Spec-format%3A-v2.0#i18n-resources

It seems though that localized resources are only added when specifying the full path to the `.lproj` directory i.e `i18n-resources: myTarget/Base.lproj`

**Comment by lyptt** [comment]
Hi @yonaskolb,

If you take a look at the [example project](https://github.com/workshop/struct/tree/master/examples/iOS_Application), you'll see that specifying the folder containing your resource files is enough. 

Also, if your resource files are in the same location as your source files, you don't need to specify a resources folder, as this is done for you by default.

**Comment by yonaskolb** [comment]
Ah ok. There was some confusion between `lproj` directories and `.lproj` directories.

There also seem to be some inconsistencies in how group names are generated (`$lang:MyTarget`) or if localized files are in any groups at all, depending on how they are brought in, but that needs more testing to provide more solid info

**Comment by lyptt** [comment]
Hi @yonaskolb,

Resource directories are namespaces by target name, whereas every other dynamic directory will have a shortname ($local, $subproj, $config, etc). This is to avoid each target's resources being lumped into one big list.

**Comment by lyptt** [comment]
I'll close this issue since you seem to have found your problem. Please let me know if this is still an issue.
