### ISSUE TITLE
Excludes

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#129]
The documentation says that excludes are defined like this:
https://github.com/workshop/struct/wiki/Spec-format%3A-v2.0#excludes

```
targets:
  My target:
    excludes:
      files:
      - "**/*.md"
      - "**/*.ipa"
      - "**/*.dSYM/**/*"
```
Given that there is a `files` property, is there any other way to define excludes? Is the `files` property required?

**Comment by lyptt** [comment]
Hi @yonaskolb,

In the future excludes will be expanded to support more than files, for now that's all excluded supports.
