### ISSUE TITLE
$config group

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#130]
Setting xcode configuration files for each config results in the creation of a top level group in the project called `$config`, even though none of the files need to be in the list of files included in the project

```
targets:
  My app:
    configurations:
      debug: configs/my-app.xcconfig
      release: configs/my-app-release.xcconfig
```

**Comment by lyptt** [comment]
Hi @yonaskolb,

This is intentional. This is done to allow you to edit the xcconfig files from within Xcode as an alternative to using the grouped build settings view.

**Comment by yonaskolb** [comment]
Ok. If multiple targets have config files though, only those for the first target are added to that group. Would `configurations` be a better name than `$config`? I guess you were trying to avoid name clashes

**Comment by lyptt** [comment]
Hi @yonaskolb, I've just tested this on a sample project with two targets that have their own unique xcconfig files:

```yaml
targets:
  My app:
    type: ":application"
    sources: sources
    configurations:
      debug: config-target.xcconfig
      release: config-target-release.xcconfig
  My other app:
    type: ":application"
    sources: sources
    configurations:
      debug: config-target-2.xcconfig
      release: config-target-2-release.xcconfig
```

With this configuration, all xcconfig files are present:

<img width="323" alt="screen shot 2017-05-23 at 06 46 16" src="https://cloud.githubusercontent.com/assets/346710/26339948/8809e8de-3f83-11e7-90c7-032dabab0b45.png">

**Comment by yonaskolb** [comment]
Yeah, I just tested this again. It does work as you say, but only if those config files are included in a target's sources. Makes sense. And if I didn't want to see the in the groups, I can leave them out of sources 👍
