### ISSUE TITLE
Shared source folders

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#133]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

[2.1.1]

## Spec version

[2.1.1]

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

If two different targets both reference the same source folder, once group is created but with duplicates of all the files.

## Reproduction steps

```
targets:
  myApp1:
    sources:
      - app
      - myApp1
  myApp2:
    sources:
      - app
      - myApp2
```

## Expected result

One group is created with a single file for each file, that has a target membership for both apps (single file reference is in compiled sources list for each app)

## Actual result

One `app` groups is created, but with 2 of every file in that directory, each for a different target

**Comment by lyptt** [comment]
Hi @yonaskolb, unfortunately this isn't a supported use case. 

With Struct, a key convention is for your filesystem to be an identical representation of your project structure, the [Migrating Xcode projects](https://github.com/workshop/struct/wiki/Migrating-Xcode-projects) page mentions this:

>The following project features are unsupported, and will not be supported by struct for the immediate / long-term future:
>
>-    Shared files between multiple targets - struct follows the approach of the filesystem representing the project file structure exactly, which is fundamentally incompatible with sharing files between targets. Each target has its own source directory. This can be worked around with creative use of file exclude rules in the spec file, but essentially goes against the grain of this tool and isn't supported.

**Comment by lyptt** [comment]
The reasoning behind this decision is that it should be obvious from a glance exactly where a file comes from, and which target it belongs to. If you're sharing files between targets, that isn't a possibility, as now you need to inspect the file to see which targets it's added to.

Struct's primary goal is enabling a simplified Xcode workflow that's more in line with more modern development workflows, like .NET Core, NodeJS, etc.

**Comment by yonaskolb** [comment]
Understood. Though in some cases it's necessary in cross platform apps.
Say you have a bunch of files, and they both need to shared between an iOS and tvOS framework. That is a common scenario. Is there another way to have cross platform frameworks in Struct?

The example above was actually for 2 application targets. I just tested with 2 framework targets, and it seems the duplication doesn't occur, but the files in the group are only targeting the first target. Both targets have all the files in their compiled sources in build phases however

**Comment by lyptt** [comment]
Hi @yonaskolb, yeah you'll probably encounter strange behaviour as it's not a supported workflow in Struct. We should add this to project linting so there's at least a warning issued to the end-user.

Cross platform frameworks is something I hadn't considered, potentially this could be solved with a higher level mechanism, for example allowing you to declare multiple platforms for a target:

```yaml
target:
  My Framework:
    platform:
    - ios
    - tv
```

Which would result in the usual pattern of two targets being defined: 'My Framework-iOS' and 'My Framework-tvOS'.

This would be much more preferable to me than exposing sharing source sets between targets.

**Comment by lyptt** [comment]
Hi @yonaskolb, this is now being tracked in #134.

**Comment by yonaskolb** [comment]
Yeah that would be great solution! Much better than currently defining duplicate targets with differing platforms. One wrinkle though would be how to reference Carthage dependancies as they are build per platform `- location: Carthage/Build/tvOS/BrightFutures.framework`. Another problem would be if that cross platform "target" referenced another cross platform "target". Struct would need to intelligently get it to reference the correct actual target.
Once possible solution is to have some sort of `platformTargets` list that acts a bit like a variant where you can specify overrides per platform that get used in the actually created target.

I actually can't really move forward without this, so I'll have to come back to struct another time.
Thanks for the responsive communication, and reading all my issues :)

**Comment by yonaskolb** [comment]
Moved comment to #134

**Comment by lyptt** [comment]
Hi @yonaskolb, yes we'll try to get this into 2.2.0, it shouldn't be too difficult to support. Thanks for filing your issues! It'll definitely allow us to make Struct better.
