### ISSUE TITLE
Headers broken in cross platform targets

### ISSUE THREAD

**Issue by yonaskolb** [workshop/struct#141]
Getting things linking properly with #140 has highlighted something. Is it possible to define headers for a framework?

Basically I have a framework A that references framework B. When an application import framework A, I don't want to have to import framework B as well. This was achieved in our project my importing framework B in Framework A's header file.
I can't see a way though to specify header files, and they don't get picked up by `sources`

**Comment by lyptt** [comment]
Hi @yonaskolb, yes it is, they should be getting picked up. Struct puts all headers in the 'Public' group.

**Comment by yonaskolb** [comment]
This may be a bug then. I have a framework target with `sources: frameworkFolder`.
There are 2 header files at `frameworkFolder/iOS/FrameworkName.h` and `frameworkFolder/tvOS/FrameworkName.h`. They show up in the group though aren't getting linked anywhere.

**Comment by yonaskolb** [comment]
Removing one of them fixes the issue. I guess if struct pulled both of these in anyway, it would be an error, as it's supposed to be one per platform.
I can probably work around this and just have a single header file for both platforms

**Comment by lyptt** [comment]
That's interesting, the folder in the middle should make the filenames be unique. I'll have a look into that.

**Comment by yonaskolb** [comment]
Also, it seems with even only file, it isn't added to public headers but instead to the copy bundle resources build phase

**Comment by yonaskolb** [comment]
Hi @lyptt. Any chance you could look at this?

**Comment by lyptt** [comment]
Hi @yonaskolb, can you try doing this with a standard target rather than a cross platform one? The example framework project has working header files:

<img width="1288" alt="screen shot 2017-05-31 at 06 53 16" src="https://cloud.githubusercontent.com/assets/346710/26617598/dbdef1ca-45cd-11e7-88ee-86caa1ffa66e.png">

**Comment by yonaskolb** [comment]
I can confirm this works properly in single platform targets, and therefore in the currently released version
