### ISSUE TITLE
undefined method `key?' for nil:NilClass

### ISSUE THREAD

**Issue by nwh** [workshop/struct#147]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

```
$ struct -v
2.2.1
```

## Spec version

Started with example from getting started guide:

```
$ cat project.yml 
---
version: 1.1.0
configurations:
  debug:
  release:
```

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

Error running `$ struct generate` on `project.yml` file from getting started guide.

## Reproduction steps

```
$ struct generate
undefined method `key?' for nil:NilClass
```

## Expected result

Expected project file to be generated.

## Actual result

Error: `undefined method `key?' for nil:NilClass`

**Comment by lyptt** [comment]
Hi @nwh, thanks for filing this issue, and apologies for the delay in getting back to you. Struct is correct in reporting an error here, as in the documentation for spec file formats < v2 profiles are required in configuration blocks.

Struct should however be reporting a nicer error than this, so I'll go head and get this fixed up for the next release.
