### ISSUE TITLE
Support for .cpp files?

### ISSUE THREAD

**Issue by steveholt55** [workshop/struct#150]
## New Issue Checklist

- [x] Updated struct to the latest version
- [x] I have read the [documentation](https://github.com/workshop/struct/wiki) to make sure my issue isn't covered already

## Struct version

2.2.1

## Spec version

2.2.1

## Which type of spec are you using?

- [x] project.yml
- [ ] project.json
- [ ] Specfile

## Context

I'm not sure if I'm missing something but I'm unable to get .cpp files in Compile Sources, but instead all .cpp files go into Copy Bundle Resources.

## Reproduction steps

project.yml
    sources:
    - /path/to/file.cpp

## Expected result

.cpp file in Compile Sources

## Actual result

.cpp file in Copy Bundle Resources

**Comment by steveholt55** [comment]
My guess is line 44 needs to change to include .cpp.  `https://github.com/workshop/struct/blob/1749e889bbbc9f9f0907b1a2e2a8945811bf86e2/lib/spec/processor/target_source.rb`.  I'd love to work on this but I have no idea how to build and use this locally.  Is there a beginners guide to contributing to this project?  I don't know much about ruby/ruby gems 😀

**Comment by lyptt** [comment]
Hi @steveholt55, thanks for filing this issue. Yeah as far as native files go we only have partial support, but it should be pretty easy to add!

In terms of running this locally, you should be able to get going by following the following steps (pretty typical for any Ruby gem):

- `gem install bundler`
- `gem install rake`

Then from the cloned repository:
- `rake install`

Then when you run `struct` from the command line, it'll be based on the code from your cloned repository directory.

Chances are we can just include `.c`, `.cpp` and `.cxx` in that check and it'll all work 😀

**Comment by steveholt55** [comment]
Thanks! I'll take a look at running this locally.

**Comment by lyptt** [comment]
This is now merged and will be in 3.1.0.
