### ISSUE TITLE
Struct public API audit

### ISSUE THREAD

**Issue by lyptt** [workshop/struct#25]
From the get-go `struct` was planned to be both a useful developer tool, _and_ a library with friendly API for use in larger tools and more complex environments.

This task is to review the current API available in `struct`, in order to ensure it's fit for purpose as a library as well as a development tool.

Proposed tasks:
- [ ] Ensure any publicly accessible APIs are fully documented
- [ ] Ensure any APIs and types not intended for public use are properly annotated as such and have appropriate access modifiers
- [ ] Assess how internal classes can be simplified to make working with them as easy as possible, e.g. builders and factories

**Comment by jcampbell05** [comment]
@lyptt I'm going to start a scaffolding tool, I could use to verify this.

**Comment by jcampbell05** [comment]
- Allow to pass version in as string and not version class
- Default to empty array when targets, variants and configurations aren’t parsed in
- Have constant for latest spec version
- Target requires 8 things to be passed in the constructor, we should have sensible defaults to most of these. We can remove profiles argument as we will be inferring, type and platform may be needed but potentially we could let developer set these later and throw assertion if they try to write without setting these for their sanity.

**Comment by jcampbell05** [comment]
There is a lot of weird quirks and non-obviousness when using profiles.
We should hide these from the API consumer as detailed in #67 to make things easier :)

**Comment by lyptt** [comment]
@jcampbell05 There's a few things here now covered by recent changes:

- [x] Have constant for latest spec version
- [x] There is a lot of weird quirks and non-obviousness when using profiles. We should hide these from the API consumer as detailed in #67 to make things easier

Remaining items are:
- [ ] Allow to pass version in as string and not version class
- [ ] Default to empty array when targets, variants and configurations aren’t parsed in

**Comment by lyptt** [comment]
Fixed in 2.0.0.
