### ISSUE TITLE
Project Linting

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#49]
I had an idea to be able to lint a project so that errors and itunes connect errors caused by wrong build settings can be discovered. 

I was going to create a project just for the linting but I was wondering if we could do this in struct as well as a `--autofix` method to fix the errors.

**Comment by lyptt** [comment]
Hi @jcampbell05, this is an excellent idea! I can't count the number of times I've been caught out by stupid configuration errors, provisioning snafus and the like when submitting builds to Apple.

This is definitely something I'd love to see in struct. Awesome idea!

**Comment by lyptt** [comment]
Some of the common issues I've encountered that are much harder to figure out:
- Framework search paths not being added for linked frameworks
- Selecting to copy an Objective-C / 'fake' framework that is only intended to be linked into a target
- Mismatched SWIFT_VERSIONs between subprojects and the main project
- Mismatched build configurations between subprojects and the main project (Xcode requires every subproject has identical build configurations to the main project)

**Comment by jcampbell05** [comment]
@lyptt  I've also had misconfigured swift build settings causing the frameworks to be generated in the wrong location for watchkit apps causing obtuse itunes errors which took 30 minutes to arrive to my inbox.

btw do you have a slack or something, perhaps we could discuss these ?

**Comment by lyptt** [comment]
@jcampbell05 I've set up a gitter and fired you over an invite, should be better for more involved discussions!

**Comment by lyptt** [comment]
@jcampbell05 Here's another one we can lint:

```
error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

		Embedded Binary Bundle Identifier:	uk.lyptt.iOSTestWatchExtension
		Parent App Bundle Identifier:		uk.lyptt.iOSTestWatchApp
```

**Comment by lyptt** [comment]
I think this can be extended out into a whole other tool, since this would be quite involved.

**Comment by jcampbell05** [comment]
@lyptt sure :) I think fastlane also have a new tool that does something like this.
