### ISSUE TITLE
Migrate to CircleCI

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#50]
I'm not sure if I noticed you tweeting TravisCI about the builds being slow but I recommend trying CircleCI they are much faster and even donate 3 containers (not sure if they are MacOS ones)

**Comment by lyptt** [comment]
Hi @jcampbell05, this could be a decent option actually. Travis is being incredibly frustrating to work with right now as they're often backlogged on macOS build nodes. My release last night was delayed by a good few hours just waiting for integration tests to actually start.

**Comment by jcampbell05** [comment]
Yeah also one of the Core Members of Cocoapods works on it so it has a lot of love when it comes to Apple Builds.

I've recently converted my projects over to CircleCI, so I will happily help to set it up but I will probably need to be added as a contributor.

**Comment by lyptt** [comment]
Sounds good! I've added you as a collaborator to the repo, so you should be able to set that up.

**Comment by lyptt** [comment]
@jcampbell05 For free OS X builds we require Circle's assistance through their billing department. I've gotten in touch.

**Comment by lyptt** [comment]
I think the current CI solution will be good enough for now. Worth re-evaluating later.
