### ISSUE TITLE
When Running Framework It should Build

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#52]
I was informed by a user of Xcake that Xcode running a framework builds it, I've tried to implement it but Xcodeproj makes it hard. But we should definatly implement it in Struct.

**Comment by lyptt** [comment]
Oh really? I'm not sure if I've ever seen that! Whenever I've manually built framework projects I could either test it with Cmd+U, or build it with Cmd+B. Could this potentially be a schemes thing?

Definitely worth investigating!

**Comment by jcampbell05** [comment]
@lyptt  I wasn't sure either but we should look into it.

Implementation wise it's a scheme thing, in Xcodeproj you basically tell it to configure the build_action to be runnable which makes it build. That said the fact Xcodeproj doesn't do this out of the box makes me question this as they usually match the default Xcode behaviour.

One hurdle, the Entry class needed to make it runnable in Xcodeproj is private so can't instansiate it.

**Comment by lyptt** [comment]
Depends on #63

**Comment by lyptt** [comment]
I believe this may now be fixed, @jcampbell05 could you verify when you get time?
