### ISSUE TITLE
Migration Guide For Xcake To Struct

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#53]
As I gradually wind down active development of Xcake, it may be a good idea to have a guide for the users who use it to migrate to struct. 

Ideally it would outline the differences in certain areas i.e using Cocoapods when needing control over headers.

**Comment by lyptt** [comment]
Yes this would be very useful! I'm unsure if as a collaborator you have wiki access. If you do, feel free to add an article detailing this process.
