### ISSUE TITLE
Fully document the nuances of struct's project generation

### ISSUE THREAD

**Issue by lyptt** [workshop/struct#54]
There are some aspects of struct that are currently undocumented, and need to be fleshed out. This task will consist of the following:

- Document how profiles, platforms, and build configurations work together to define configuration for your project
- More usage examples both simple and complex to fully illustrate various usage scenarios for struct

**Comment by jcampbell05** [comment]
Do we have documentation on variants. Also another thing that is useful to have is a list of things Struct can hand in the Xcode Project. People always requested this from me in Xcake, have a look here https://github.com/jcampbell05/xcake/tree/master/docs

I've also considered explaining the project file format for contributors too.

**Comment by lyptt** [comment]
Hi @jcampbell05, yes we have documentation for variants! Please check out the [wiki](https://github.com/lyptt/struct/wiki) to see what documentation we currently have in place.

**Comment by lyptt** [comment]
Documentation has been improved during Struct 2.x, however this will be an on-going task going forward.
