### ISSUE TITLE
Make Specfiles for projects to drive adoption

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#58]
One thing suggested to me for Xcake but I never did is to make PRs for several successful projects or open source apps and submit a Specfile for them to start using Struct.

Obviously a lot of projects may not need struct as they will use Cocoapods to handle the project but may drive adoption :) 

Otherwise its just spreading the word :) (I'm thinking of blogging about why people should use xcode generators)

**Comment by lyptt** [comment]
Ah this is a great idea! I know Fastlane has a 'recipes' section where popular companies demonstrate their Fastfiles. We could definitely do something similar!
