### ISSUE TITLE
Add Issue Template

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#61]
To stop annoying people like me asking not very detailed issues :) 
We should ask for things like Xcodeproj version, Struct version and example Specfile. 

@maximkhatskevich is very good with documentation and stuff so maybe he can suggest a template :)

**Comment by lyptt** [comment]
Good point! I'm unaware of how to do this, some research needed 👍

**Comment by maximkhatskevich** [comment]
I'm happy to help with documentation on Struct, but not sure what exactly do you mean @jcampbell05 Add a special paragraph in Readme file how to file an issue on Struct GitHub repo?

**Comment by jcampbell05** [comment]
@maximkhatskevich I'm meaning this :) https://github.com/blog/2111-issue-and-pull-request-templates but documentation would be great too :)

**Comment by maximkhatskevich** [comment]
Interesting, didn't know about that :) Okay, I'll take a look.

**Comment by lyptt** [comment]
The issue template is now added.
