### ISSUE TITLE
Release and Debug configurations are not treated same as in Xcode

### ISSUE THREAD

**Issue by jcampbell05** [workshop/struct#81]
In Xcode these configurations are capitalized but Struct they are treated as being lowercase, thus "Release" doesn't default to having a release type but "release" does.

(I know it's one of these quirky things)

**Comment by lyptt** [comment]
Yeah this is mainly a struct opinionated thing. One solution I had was to recognise both 'debug' and 'Debug' without having to specify the type. I think this would work well 😄

**Comment by jcampbell05** [comment]
@lyptt Yeah that would make sense :)

**Comment by lyptt** [comment]
Fixed in 2.0.0.
