### ISSUE TITLE
Community Group?

### ISSUE THREAD

**Issue by robertjpayne** [workshop/struct#85]
Hi there,

I'm *very* keen to help contribute on this project, but is there a Slack/Gitter/IRC group for contributors? I have a few questions about the codebase before I start tweaking.

Cheers!

**Comment by lyptt** [comment]
Hey @robertjpayne, thanks for filing this issue! Yes we have a Gitter you can chat on [here](https://gitter.im/workshop/Lobby) - it's fairly fresh as we've only just recently transferred over from a private account to an organisation. Feel free to post your questions there!
