### ISSUE TITLE
Input and Output files for a script build phase

### ISSUE THREAD

**Issue by maximkhatskevich** [workshop/struct#89]
I'm wondering how can we specify extra parameters that Xcode allows to pass in every Script build phase (see screenshot attached).

<img width="631" alt="screen shot 2017-03-26 at 2 14 06 pm" src="https://cloud.githubusercontent.com/assets/2624646/24331156/c3aa3dbc-122e-11e7-823b-c4bc5bd0d943.png">

**Comment by lyptt** [comment]
@maximkhatskevich for your particular use case, you probably don't need either. Environment variables can be directly referenced in a build script.

**Comment by maximkhatskevich** [comment]
Thanks, I didn't know that, but feel free to consider it as a feature request for future releases!

**Comment by yonaskolb** [comment]
This would be useful for integrating Carthage, for adding the `copy-frameworks` script which takes a bunch of input files as mentioned here https://github.com/Carthage/Carthage#getting-started
Is there a better way to integrate Carthage using Struct?

**Comment by lyptt** [comment]
Hi @yonaskolb. Struct was actually designed originally to only support Carthage, and on a fairly big project we never needed the copy-frameworks command. On a fairly large codebase with lots of mixed dependencies, we didn't have any issue with Carthage frameworks.

This is something I'm actively considering for 2.2.0, but I suggest trying without the script for the time being.
