### ISSUE TITLE
Source options probably return strange warning

### ISSUE THREAD

**Issue by maximkhatskevich** [workshop/struct#90]
I'm getting message like this "Warning: Target Tests's source options was not a Hash. Ignoring source options..." when generating project from a `project.yml` file with Struct 1.3.0, but I do not have `source_options` entries in my spec file.

**Comment by lyptt** [comment]
Hi @maximkhatskevich, can you paste your project.yml here? I have not observed these warnings when testing with existing project files.

**Comment by lyptt** [comment]
Thanks @maximkhatskevich, looks like I was a bit too strict with one of the parsing checks. Fix coming shortly 👍

**Comment by maximkhatskevich** [comment]
Glad to help! :)

**Comment by lyptt** [comment]
Fixed in 1.3.1 - now released 🚀
