### ISSUE TITLE
Struct does not set "Host application" for unit tests target

### ISSUE THREAD

**Issue by maximkhatskevich** [workshop/struct#92]
even if I have set the reference in 'project.yml' file like this:

```Ruby
targets:
  MyApp:
    platform: "ios"
    type: ":application"
```

and then later...

```Ruby
  Tests:
      platform: "ios"
      type: ":bundle.unit-test"
      references:
      - "MyApp"
```

**Comment by maximkhatskevich** [comment]
Struct v.1.3.1

**Comment by lyptt** [comment]
You're correct @maximkhatskevich, it doesn't do this automatically. Please see the [iOS Application sample project](https://github.com/workshop/struct/blob/master/examples/iOS_Application/project.yml) line 115 for an example of how this is done.

**Comment by maximkhatskevich** [comment]
Okay, I see, thanks!
