### ISSUE TITLE
Add support for sending opt-in telemetry data so we can see how Struct is being used

### ISSUE THREAD

**Issue by lyptt** [workshop/struct#97]
As more people use Struct it would be useful to know how Struct is being used, so we can determine:

- [ ] Which features are being used the most, and are of most importance when fixing issues?
- [ ] Which features are being used the least, and are of a lower priority to fix?
- [ ] Which features aren't being used at all, and could be removed?
- [ ] Which features need performance improvements?

This would help us keep the maintenance burden as low as possible, and get an insight into where changes need to be made from the perspective of active users.

If this were to be implemented, the following features would be necessary:

- [ ] Ensure all telemetry data is completely anonymous and only consists of metrics, e.g. no target names, configuration settings or any other user content
- [ ] Provide the user with the option to inspect the telemetry data before it's sent, so they can choose to abort this at any time
- [ ] Provide a location where telemetry data can be inspected and analysed
- [ ] Ensure a reasonable data retention limit is set

@jcampbell05 I'd love to get your thoughts on this one.

**Comment by jcampbell05** [comment]
Sounds good to me 😀 defiantly is hard to choose the trade offs without the dstab
